[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "lightning>=2.5.5",
    "omegaconf>=2.3.0",
    "pytorchwildlife>=1.2.4.1",
]
